FROM php:8.1-fpm-alpine

RUN apk add --no-cache \
        bash \
        build-base \
        libpng-dev \
        libpq-dev \
        libxml2-dev \
        icu-dev \
        nodejs \
        npm \
    && docker-php-ext-install \
        gd \
        intl \
        pdo_pgsql

SHELL ["/bin/bash", "-c"]

# USER www-data
WORKDIR /var/www/html

COPY --from=composer /usr/bin/composer /usr/bin/composer

# CMD [ "php-fpm" ]
ENTRYPOINT [ "sh", "-c", "php-fpm" ]
EXPOSE 9000
