version: "3.9"
services:
  gateway:
    build: ./app/gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - web_assets:/var/www/html/public/dist:ro
  web:
    build: ./uf-web
    restart: always
    expose:
      - "9000"
    environment:
      - APP_ENV=${SYMFONY_ENV}
      - APP_SECRET=${SYMFONY_SECRET}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/uffn
    depends_on:
      - db
    volumes:
      - web_assets:/var/www/html/public/dist
  db:
    build: ./app/database
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=uffn
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   expose:
  #     - "6379"
volumes:
  web_assets:
