parameters:
    env(DATABASE_URL): '__CHANGEME__DEFAULT_DB_CONN_STRING_FOR_DOCKER__'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
